### PR TITLE
fixed issue #9 url problem fixed

### PR DESCRIPTION
**Pull request by Hallcoder**

### CODE REVIEW

**Comment by Hallcoder** [comment]
The url.parse method that was not working now works after installing the right dependency

**Comment by stipsan** [comment]
Could you give us a repro case of when it doesn't work? :relaxed:

**Comment by stipsan** [comment]
Closing this as the upcoming `v5` release solves this by using the [`Web URL API`](https://developer.mozilla.org/en-US/docs/Web/API/URL) for parsing, which doesn't need an npm dependency :relaxed:

**Comment by Hallcoder** [comment]
That's great as it's resolved!

**Pull request closed without merging**
